---
- name: "Mario and Tetris installation"
  become: yes
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - files/secrets/credentials.yml
  tasks:
    - name: Create docker containers
      docker_container:
        name: "super-mario"
        image: "pengbai/docker-supermario"
        state: started
        restart: "yes"
        ports: "9001:8080"
      tags: mario  

