---
    - name: Install pre-requisite packages
      yum:
        name: "{{item}}"
        state: latest
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python3
      when: ansible_os_family == "RedHat"

    - name: Install Docker
      yum: 
        name: docker 
        state: latest
      when: ansible_os_family == "RedHat"
    - name: Start and enable the Docker daemon
      service: 
        name: docker 
        state: started 
        enabled: yes

    - name: Add remote user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/bin/docker-compose     
        mode: 'u+x,g+x' 
    - name: create www data
      user: 
        name:  www-data
        state: present

    - name: Install docker-compose on target
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/bin/docker-compose     
        mode: 'u+x,g+x'           
...
